version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - mvn surefire-report:report
reports:
  SurefireReports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'